### ISSUE TITLE
About Open Computers Support

### ISSUE THREAD

**Issue by NightScale5755** [SteveTheEngineer/Immersive-Vehicles-Remote-Control#8]
Hello, me again. So today I was looking at CC:Tweaked, and the fact the authors of that don't want to and won't add an option for their computers needing energy got me thinking about something.
Then I noticed on this mod's curse page that OC is still a feasible option.
So if I may, why was OC dropped altogether?
Personally I think it would be better for modpack authors who rely on OC for other mods (ImmersiveRailroading), to maybe have the choice between using OC or CC:T. 
No matter the answer, I do support this mod, and look forward to future updates. Keep up the GREAT work!

**Comment by SteveTheEngineer** [comment]
I've rewritten the mod to work with ComputerCraft instead of OpenComputers, so that you could choose between those two instead of being forced to use a specific one of them. To access these blocks from OpenComputers, use the Adapter block (you'll still need CC: Tweaked to be installed alongside OpenComputers). The methods, their signatures, and return parameters stay the same, see [the documentation](https://github.com/SteveTheEngineer/Immersive-Vehicles-Remote-Control/tree/master/src/main/resources/assets/computercraft/lua/rom/help).

**Comment by NightScale5755** [comment]
I see. 
I also see I completely forgot to mention what I wanted to ask to begin with, lol.
Would it be at all possible to make CC:T a soft dependency? So OC can be used without CC:T? Just curious.

**Comment by SteveTheEngineer** [comment]
> I see. I also see I completely forgot to mention what I wanted to ask to begin with, lol. Would it be at all possible to make CC:T a soft dependency? So OC can be used without CC:T? Just curious.

It is possible. What I'd suggest doing right now is using CraftTweaker to remove the recipes and hide all of the items from CC: Tweaked.

**Comment by NightScale5755** [comment]
Alrighty. Sounds good. Keep up the great work, ok?

**Comment by SteveTheEngineer** [comment]
> Alrighty. Sounds good. Keep up the great work, ok?

Sure. Close this issue if you don't have any other questions. (I also honestly don't have much interest in working on IVRC anymore, however I'll keep updating it knowing that some people are using it)

**Comment by NightScale5755** [comment]
ah. Fair nuff. Have a good one!
